# Local database service
services:
  db:
    container_name: grace-db
    image: postgres:16.3
    environment:
      POSTGRES_DB: grace
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
