CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  email CITEXT UNIQUE NOT NULL,
  password BYTEA NOT NULL,
  verified BOOLEAN NOT NULL DEFAULT FALSE,
  friend_hash BYTEA UNIQUE,
  follower_hash BYTEA UNIQUE,
  updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
  created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW()
);