CREATE TABLE IF NOT EXISTS cards (
  id BIGSERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  data JSONB NOT NULL,
  created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
  template_id BIGINT REFERENCES templates(id),
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);